#ALGORITMO QUE CALCULA O DELTA USANDO OS VALORES DIGITADOS PELO USUARIO
A=int(input("DIGITE UM VALOR: "))
B=int(input("DIGITE UM SEGUNDO VALOR: "))
C=int(input("DIGITE UM TERCEIRO VALOR: "))
DELTA=B**2 -4*A*C
print("O VALOR DE DELTA É:",DELTA)